#pragma once
#include <glm/glm.hpp>
#include <array>
#include <string>
#include <sstream>
#include <iostream>

/**
 * @brief Represents the geometric and visual data for a single vertex, 
 *        used and transformed throughout the rasterization pipeline stages.
 */
struct VertexData {

    // Loaded from file
    glm::vec3 pointObjectCoordinates; // Position of the vertex in object coordinates
    glm::vec3 normalObjectCoordinates; // Normal vector at the vertex in object coordinates
    glm::vec2 textureCoordinates; // Texture coordinates for the vertex
    glm::vec3 color;

    // Calculated in vertex processing and used by face processing
    glm::vec3 pointEyeCoordinates; // Position of the vertex in eye coordinates
    glm::vec3 pointWindowCoordinates;   // Position of the vertex in window coordinates
    glm::vec3 normalEyeCoordinates; // Normal vector at the vertex in eye coordinates
    float lightingIntensity0to1;

    // Constructors
    VertexData() = default;
    
    VertexData(const glm::vec3& pointObj, const glm::vec3& normalObj, const glm::vec2& texCoord, const glm::vec3& col)
        : pointObjectCoordinates(pointObj), 
          normalObjectCoordinates(normalObj), 
          textureCoordinates(texCoord), 
          color(col),
          pointEyeCoordinates(0.0f),
          pointWindowCoordinates(0.0f),
          normalEyeCoordinates(0.0f),
          lightingIntensity0to1(0.0f) {}

    /**
     * @brief Returns a string representation of the vertex for debugging.
     * @return Formatted string containing the vertex coordinates.
     */
    std::string toString() const {
        std::ostringstream oss;
        oss << "Vertex [p=(" << pointObjectCoordinates.x << ", "
            << pointObjectCoordinates.y << ", "
            << pointObjectCoordinates.z << ")]";
        return oss.str();
    }
};

/**
 * @brief Represents a single triangular polygon within an object mesh, storing 
 *        indices that map to a global vertex array alongside face-specific attributes.
 */
struct TriangleFace {
    std::array<int, 3> indices;
    glm::vec3 color;
    glm::vec3 normal;

    TriangleFace(const std::array<int, 3>& indicesList, const glm::vec3& col, const glm::vec3& norm = glm::vec3(0.0f)) 
                : indices(indicesList), color(col), normal(norm) {}

    std::string toString() const {
        std::ostringstream oss;
        oss << "TriangleFace [indices=" << indices[0] << ", " << indices[1] << ", " << indices[2] 
            << ", color=" << color.x << "," << color.y << "," << color.z << "]";
        return oss.str();
    }
};

/**
 * @brief Holds the interpolated payload for a single potential pixel (fragment) 
 *        generated by the rasterizer, used to compute the final output color.
 */
struct FragmentData {
    glm::vec3 pixelColor; // Color of the fragment
    glm::vec3 pointEyeCoordinates; // Position of the fragment in eye coordinates
    glm::vec3 normalEyeCoordinates; // Normal vector at the fragment in eye coordinates
    glm::vec2 textureCoordinates; // Texture coordinates for the fragment
    float pixelIntensity0to1; // Pixel intensity for the fragment
    float levelOfDetail; // Level of detail for Trilinear Filtering

    // Constructor
    FragmentData() = default;
};

/**
 * @brief Represents a mathematical plane in 3D space defined by a point and a normal, 
 *        primarily used to define the camera's view frustum boundaries for geometry clipping.
 */
struct ClippingPlane {
    glm::vec3 pointOnPlane;
    glm::vec3 normal;

    ClippingPlane(const glm::vec3& point, const glm::vec3 norm) : pointOnPlane(point), normal(norm) {};
};