#define SDL_MAIN_HANDLED
#include <iostream>
#include <vector>
#include <numeric>
#include <random>
#include <algorithm>
#include <windows.h> // For the File Open Dialog
#include <SDL.h>
#include <glm/glm.hpp>
#include <magic_enum.hpp> // For ExerciseEnum string conversion

// ImGui Headers
#include "imgui.h"
#include "imgui_impl_sdl2.h"
#include "imgui_impl_sdlrenderer2.h"

#include "RayTracerWorld.h"
#include "SavedParams.h"
#include "DefaultParams.h"
#include "ExerciseEnum.h"
#include "Utilities.h"

int main() {
    SavedParams params;

    // --- SDL Initialization ---
    if (SDL_Init(SDL_INIT_VIDEO) < 0) {
        std::cerr << "Failed to initialize SDL: " << SDL_GetError() << std::endl;
        return -1;
    }

    SDL_Window* window = SDL_CreateWindow("3D Rasterization App (C++)",
                                          SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                                          DefaultParams::IMAGE_WIDTH, DefaultParams::IMAGE_HEIGHT, 
                                          SDL_WINDOW_SHOWN);
    SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
    SDL_Texture* texture = SDL_CreateTexture(renderer, SDL_PIXELFORMAT_ARGB8888, 
                                             SDL_TEXTUREACCESS_STREAMING, 
                                             DefaultParams::IMAGE_WIDTH, DefaultParams::IMAGE_HEIGHT);

    // --- ImGui Initialization ---
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO(); (void)io;
    ImGui::StyleColorsDark();
    ImGui_ImplSDL2_InitForSDLRenderer(window, renderer);
    ImGui_ImplSDLRenderer2_Init(renderer);

    // --- Rendering Variables ---
    std::vector<uint32_t> pixelBuffer(DefaultParams::IMAGE_WIDTH * DefaultParams::IMAGE_HEIGHT, 0xFF323232);
    std::vector<int> pixelIndices(DefaultParams::IMAGE_WIDTH * DefaultParams::IMAGE_HEIGHT);
    std::iota(pixelIndices.begin(), pixelIndices.end(), 0);
    
    std::random_device rd;
    std::mt19937 g(rd());
    std::shuffle(pixelIndices.begin(), pixelIndices.end(), g);

    RayTracerWorld rayTracerWorld(DefaultParams::IMAGE_WIDTH, DefaultParams::IMAGE_HEIGHT, 90.0f);
    bool isLoaded = rayTracerWorld.load(params.getRtModelFileName()); 
    rayTracerWorld.setRenderingParams(params.getDepthOfRayTracing());
    rayTracerWorld.setExercise(params.getRtExercise());

    // UI Data
    int selectedExercise = static_cast<int>(params.getRtExercise());

    // Main Loop
    bool isRunning = true;
    size_t currentIndex = 0;
    const size_t PIXELS_PER_FRAME = 5000;

    while (isRunning) {
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            ImGui_ImplSDL2_ProcessEvent(&event); // Pass events to ImGui
            if (event.type == SDL_QUIT) isRunning = false;
        }

        // Start the ImGui frame
        ImGui_ImplSDLRenderer2_NewFrame();
        ImGui_ImplSDL2_NewFrame();
        ImGui::NewFrame();

        // Build the UI Window
        ImGui::Begin("Controls");
        
        // 1. Load Model Button
        if (ImGui::Button("Open Model File...")) {

            // Passing "model" as the extension and an empty string "" to let Windows use the last visited directory
            std::string newPath = Utilities::openFileChooser("model", "");

            if (!newPath.empty()) {

                // Convert the Windows path into a safe relative path
                std::string relativePath = Utilities::getRelativePath(newPath);

                // Save the relative path to parameters.json
                params.setRtModelFileName(relativePath);
                isLoaded = rayTracerWorld.load(params.getRtModelFileName());
                
                // Reset rendering state
                currentIndex = 0;
                std::fill(pixelBuffer.begin(), pixelBuffer.end(), 0xFF323232);
                std::shuffle(pixelIndices.begin(), pixelIndices.end(), g);
            }
        }
        
        // Show current file
        ImGui::TextWrapped("Model: %s", params.getRtModelFileName().c_str());
        ImGui::Separator();

        // 2. Exercise Selection Dropdown (Powered by magic_enum)
        std::string currentExerciseName = std::string(magic_enum::enum_name(static_cast<RayTracingExerciseEnum>(selectedExercise)));
        
        if (ImGui::BeginCombo("Exercise", currentExerciseName.c_str())) {
            
            // Loop automatically through all enum values generated by magic_enum
            for (const auto& val : magic_enum::enum_values<RayTracingExerciseEnum>()) {
                bool isSelected = (selectedExercise == static_cast<int>(val));
                
                // Safely extract the string representation
                std::string itemName = std::string(magic_enum::enum_name(val));
                
                if (ImGui::Selectable(itemName.c_str(), isSelected)) {
                    selectedExercise = static_cast<int>(val);
                    params.setRtExercise(static_cast<RayTracingExerciseEnum>(selectedExercise));
                    rayTracerWorld.setExercise(params.getRtExercise());
                    
                    // Reset rendering state
                    currentIndex = 0;
                    std::fill(pixelBuffer.begin(), pixelBuffer.end(), 0xFF323232);
                    std::shuffle(pixelIndices.begin(), pixelIndices.end(), g);
                }
                
                // Set the initial focus when opening the combo
                if (isSelected) {
                    ImGui::SetItemDefaultFocus();
                }
            }
            ImGui::EndCombo();
        }
        
        ImGui::End();

        // Ray Tracing Processing
        if (isLoaded && currentIndex < pixelIndices.size()) {
            size_t end = std::min(currentIndex + PIXELS_PER_FRAME, pixelIndices.size());
            for (; currentIndex < end; ++currentIndex) {
                int idx = pixelIndices[currentIndex];
                int x = idx % DefaultParams::IMAGE_WIDTH;
                int y = idx / DefaultParams::IMAGE_WIDTH;

                glm::vec3 color = rayTracerWorld.renderPixel(x, y);
                
                uint8_t r = static_cast<uint8_t>(std::min(color.r * 255.0f, 255.0f));
                uint8_t g_c = static_cast<uint8_t>(std::min(color.g * 255.0f, 255.0f));
                uint8_t b = static_cast<uint8_t>(std::min(color.b * 255.0f, 255.0f));
                
                int flipped_y = DefaultParams::IMAGE_HEIGHT - 1 - y;
                pixelBuffer[flipped_y * DefaultParams::IMAGE_WIDTH + x] = (0xFF << 24) | (r << 16) | (g_c << 8) | b;
            }
            SDL_UpdateTexture(texture, nullptr, pixelBuffer.data(), DefaultParams::IMAGE_WIDTH * sizeof(uint32_t));
        }

        // --- Drawing ---
        ImGui::Render();
        SDL_RenderClear(renderer);
        SDL_RenderCopy(renderer, texture, nullptr, nullptr); // Draw the ray-traced image
        ImGui_ImplSDLRenderer2_RenderDrawData(ImGui::GetDrawData()); // Draw ImGui ON TOP of the image
        SDL_RenderPresent(renderer);
    }

    // --- Cleanup ---
    ImGui_ImplSDLRenderer2_Shutdown();
    ImGui_ImplSDL2_Shutdown();
    ImGui::DestroyContext();

    SDL_DestroyTexture(texture);
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();

    return 0;
}